### ISSUE TITLE
How to create a post API?

### ISSUE THREAD

**Issue by jeevan-lal** [pnglabz/cakephp-rest#1]
Hello, Sir 

I am using this library but I do not create a POST API.
I am Using `CakePHP 3.6`

**Comment by narendravaghela** [comment]
Hey, there is nothing to do with the plugin. It just provides a way to send the response back in JSON format. You can make any type of request as you do normally with CakePHP.

Now, what exactly you want to do? Please explain your problem in details, so I can help you out.

**Comment by jeevan-lal** [comment]
How can I perform a POST request using this Plugin?
can you give me an example?
thanks

**Comment by narendravaghela** [comment]
Okay, below is an example of configuring a POST request which returns JSON response using this plugin.

Assuming your CakePHP application is running at http://cakephprest.local,

1. Setup a route

**Comment by narendravaghela** [comment]
Okay, below is an example of configuring a POST request which returns JSON response using this plugin.

Assuming your CakePHP application is running at http://cakephprest.local,

1. Setup a route

In your `config/routes.php`, define a route.

```php
$routes->connect('/foo/bar', ['controller' => 'Foo', 'action' => 'bar', 'isRest' => true]);
```

2. Create a `FooController` and define the `bar` action which accepts `POST` request only.

```php
<?php

namespace App\Controller;

use Rest\Controller\RestController;

/**
 * Foo Controller
 *
 */
class FooController extends RestController
{

    /**
     * bar method
     *
     * @return Response|void
     */
    public function bar()
    {
        // Only accept POST request
        $this->request->allowMethod(['post']);

        // prepare your data to send back as response
        $reqData = $this->request->getData();
        $bar = [
            'reqData' => $reqData,
            'falanu' => [
                'dhikanu',
                'tamburo'
            ]
        ];

        $this->set(compact('bar'));
    }
}
```

3. Make a request

You can make a request using `curl` or `Postman` or similar ones, below is a basic `curl` request example.

```php
<?php
$url = 'http://cakephprest.local/foo/bar';

try{
    $postFields = [
        'email' => 'youremail@yourdomain.com',
        'password' => 'yourpassword'
    ];
    
    $ch = curl_init();
    curl_setopt_array($ch, array(
        CURLOPT_URL => $url,
        CURLOPT_POST => true,
        CURLOPT_POSTFIELDS => $postFields,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_HEADER => false,
        CURLOPT_SSL_VERIFYPEER => false
    ));
    
    $result=curl_exec ($ch);
    curl_close ($ch);
    
    echo $result;	
}
catch(Exception $ex){
	echo $ex->getMessage();
}
```

And the successful call will return below output,

```json
{
    "status": "OK",
    "result": {
        "reqData": {
            "email": "youremail@yourdomain.com",
            "password": "yourpassword"
        },
        "bar": {
            "falanu": [
                "dhikanu",
                "tamburo"
            ]
        }
    }
}
```

**Comment by jeevan-lal** [comment]
Thank for example, it is working fine
