### ISSUE TITLE
CakePHP 4

### ISSUE THREAD

**Issue by wsergent** [pnglabz/cakephp-rest#11]
Is there any chance of an official update to this plugin to support CakePHP 4?
At present, we are updating an application, and have successfully ported everything to Cake4 via the [upgrade guide](https://book.cakephp.org/4/en/appendices/4-0-upgrade-guide.html).
The last step is the actual update to CakePHP 4 via a composer update, which can't happen while the `sprintcube/cakephp-rest` plugin is requiring `"cakephp/cakephp": "^3.4.0"`

**Comment by narendravaghela** [comment]
Hi @wsergent 

We are not actively maintaining this plugin. If you want to use this plugin, please update its codebase as per the CakePHP 4.

**Comment by wsergent** [comment]
Thanks for the response, completely understand.
I've instead gone without the plugin entirely as it was easy enough to replicate the core functionality in the base CakePHP 4 code using their Authentication plugin.
Thank you again for the plugin, it is/was an integral part of our CakePHP 3 projects.
