### ISSUE TITLE
Please add support for version 4

### ISSUE THREAD

**Issue by jdecode** [pnglabz/cakephp-rest#4]
Please add support for version 4.

**Comment by matibaski** [comment]
Same here. Would be awesome.

**Comment by rajjecrc** [comment]
is there any support for version cakephp 4.x

**Comment by narendravaghela** [comment]
There is no active development going on for this plugin. Also, there is no plan to make it compatible with CakePHP v4 in the near future as I am quite busy with other stuff and not getting time to maintain this plugin.

Alternatively, you can clone this repo and modify it to work with CakePHP 4.

Thanks
